# Argonaut project coordinates (CalVer YYYY.MM.MICRO)
group=it.hydr4
version=2026.08.1

# JVM
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

# Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Kotlin
kotlin.code.style=official
